### ISSUE TITLE
getForecastIconText reporting issues. 

### ISSUE THREAD

**Issue by jpaustin** [fowlerk/ESP8266-Color-Weather-Station-v11d#2]
1. Downloaded fresh
2. Replace the Wonderground libraries with the version you include
3. Compile shows the following error:

Arduino: 1.8.1 (Windows 8.1), Board: "WeMos D1 R2 & mini, 80 MHz, 921600, 4M (3M SPIFFS)"

WeMos_Weather_Station_Color_OnDemandPortal_DST_11d:1212: error: 'class WundergroundClient' has no member named 'getForecastIconText'

   String weatherIcon = wunderground.getForecastIconText(dayIndex);

                                     ^

exit status 1
'class WundergroundClient' has no member named 'getForecastIconText'

**Comment by fowlerk** [comment]
Hmm, strange.  This is the new function I added and the one change that is pending the merge.  I verified that the posted library includes the function referenced.  Double check that you have replaced the original Weather Underground client components in the library folder.  You might even navigate to that location, open both the .h and .cpp files, and look to verify that the referenced function (getForecastIconText) is included there.  Sounds like the compiler is picking up an old library somewhere.

I have not tried downloading the entire posted distribution and building it from scratch, so if you can't resolve it, I'll try that to see if I can replicate the issue in the next few days.

**Comment by jpaustin** [comment]
Odd I double checked my Arduino/libraries directory and see the original library. I replaced the .cpp and .h files and kept the old ones as a rename. I can try to completely remove the old ones in case there is something odd going on.  I look through the new ones and see your comments and new code so this one is a bit strange. Agree it may be pulling something from a prior library. Any way to see where the present compile is pulling from? I 'll play around with verbose compile and see if I can come up with anything.

**Comment by jpaustin** [comment]
Dumb mistake on my part. I thought I was looking at my libraries.... Arduino was configured for an old drive in my system. I recently upgraded the drives and such and didn't move the pointer. Duhh!

**Comment by fowlerk** [comment]
No problem!  Glad it was something simple!
