### ISSUE TITLE
Upload utility help

### ISSUE THREAD

**Issue by jpaustin** [fowlerk/ESP8266-Color-Weather-Station-v11d#3]
I did this step: Install the ESP8266 Sketch Data Upload tool from here: https://github.com/esp8266/arduino-esp8266fs-plugin

But in my version (1.81) I am not seeing the utility. I created the directory structure as indicated but I opnly see a src/JAVA type file and nothing with an extension of jar. Is there some new way to get the utility to work with 1.81?

**Comment by jpaustin** [comment]
Sorry I also resolved this one. I picked up the wrong zip file. Please close. 

Got this version 11 to work! Thanks.

**Comment by fowlerk** [comment]
Ahh, good, you got it to work!  I was just typing up a response when I saw you solved this.  Yeah, the instructions are a little misleading and easy to overlook the step that points you to the correct installation zip.

Let me know what you think after you run it for awhile...
